import type { Recipe } from "@/components/RecipeCard";

// Temporary mock data source. Replaced by real Firestore queries in Phase 4
// of the migration plan (see /Users/apple/.claude/plans — recipes collection).
export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: "jollof-rice",
    title: "The Perfect Party Jollof Rice",
    category: "Nigerian",
    time: "45 min",
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyaWNlJTIwc3RldyUyMHNvdXAlMjBib3dsJTIwZm9vZHxlbnwxfHx8fDE3ODIwNjc1MDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Smoky, rich and deeply flavoured — the way it's meant to be made at parties.",
    author: "Chizzy",
    rating: 4.9,
    saves: 2340,
    servings: 6,
    ingredients: [
      { amount: "3 cups", item: "Long grain parboiled rice, washed" },
      { amount: "500g", item: "Chicken pieces, seasoned" },
      { amount: "1 can (400g)", item: "Plum tomatoes, blended" },
      { amount: "3 tbsp", item: "Tomato paste" },
      { amount: "1 large", item: "Onion, half blended + half sliced" },
      { amount: "2 tbsp", item: "Groundnut oil" },
      { amount: "2 cups", item: "Chicken stock (hot)" },
      { amount: "1 tsp", item: "Curry powder" },
      { amount: "1 tsp", item: "Thyme" },
      { amount: "2", item: "Bay leaves" },
      { amount: "2 cubes", item: "Knorr chicken seasoning" },
      { amount: "Salt", item: "To taste" },
    ],
    steps: [
      { step: 1, title: "Season and cook the chicken", time: "20 min", desc: "Season chicken pieces with curry, thyme, seasoning cubes, onion powder and salt. Add to a pot with 1 cup water. Cook on medium heat for 20 minutes until tender. Reserve the stock." },
      { step: 2, title: "Fry down the tomato base", time: "15 min", desc: "In a large pot, heat the groundnut oil. Add sliced onions and fry until golden. Add tomato paste and fry for 3 minutes. Pour in the blended tomatoes and peppers. Fry on medium heat, stirring occasionally, until the oil floats on top (about 15 minutes). This is key to great jollof." },
      { step: 3, title: "Add the rice and stock", time: "5 min", desc: "Once the tomato base is fried, add the chicken stock. Season with curry, thyme, and remaining seasoning cubes. Taste — it should be slightly saltier than you want, as the rice will absorb much of it." },
      { step: 4, title: "Cook the rice low and slow", time: "30 min", desc: "Add the washed rice to the pot. Stir to combine. Place the bay leaves on top. Cover tightly with foil first, then the lid. Cook on LOW heat for 30–35 minutes without lifting the lid. The steam is your secret weapon." },
      { step: 5, title: "Char for the smoky finish", time: "5 min", desc: "In the last 5 minutes, raise the heat to HIGH for exactly 3 minutes to create that beautiful party jollof smoky base. Remove from heat. Let rest 5 minutes before opening." },
    ],
    notes: [
      "Never lift the lid while the rice is steaming — patience is everything.",
      "The key to smoky party jollof is the last high-heat char step. Don't skip it.",
      "Use hot stock, not cold water, to prevent the rice from getting mushy.",
      "If your tomato base spatters too much, half-cover the pot and reduce heat.",
      "Leftover jollof reheats beautifully with a splash of water and covered on low heat.",
    ],
  },
  {
    id: "egusi-soup",
    title: "Rich Egusi Soup with Assorted Meat",
    category: "Nigerian",
    time: "1 hr 20 min",
    difficulty: "Hard",
    image: "https://images.unsplash.com/photo-1665593998976-d957f2827fe7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHxyaWNlJTIwc3RldyUyMHNvdXAlMjBib3dsJTIwZm9vZHxlbnwxfHx8fDE3ODIwNjc1MDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "A classic Nigerian egusi soup loaded with flavour, palm oil, and assorted proteins.",
    author: "Chizzy",
    rating: 4.8,
    saves: 1890,
    servings: 6,
    ingredients: [
      { amount: "2 cups", item: "Ground egusi (melon seeds)" },
      { amount: "1kg", item: "Assorted meat (cow leg, shaki, beef)" },
      { amount: "300g", item: "Stockfish and dried fish, soaked" },
      { amount: "½ cup", item: "Palm oil" },
      { amount: "1 large", item: "Onion, chopped" },
      { amount: "2 cups", item: "Blended tomato and pepper mix" },
      { amount: "2 cups", item: "Pumpkin leaves (ugu), shredded" },
      { amount: "2 tbsp", item: "Ground crayfish" },
      { amount: "2 cubes", item: "Seasoning cubes" },
      { amount: "Salt", item: "To taste" },
    ],
    steps: [
      { step: 1, title: "Cook the assorted meat", time: "30 min", desc: "Season and boil the meat, stockfish, and dried fish together with onion and seasoning cubes until tender. Reserve the stock." },
      { step: 2, title: "Fry the egusi", time: "10 min", desc: "Heat palm oil in a pot, add chopped onions and fry briefly. Add the ground egusi in lumps and fry, stirring occasionally, until it turns slightly golden." },
      { step: 3, title: "Add tomato base and stock", time: "10 min", desc: "Stir in the blended tomato and pepper mix and the reserved meat stock. Bring to a simmer." },
      { step: 4, title: "Add the proteins", time: "15 min", desc: "Add the cooked meat, stockfish, dried fish and crayfish. Simmer for 15 minutes, stirring occasionally so the egusi doesn't stick to the bottom." },
      { step: 5, title: "Finish with vegetables", time: "5 min", desc: "Stir in the shredded ugu leaves, adjust salt and seasoning, and simmer for a final 5 minutes." },
    ],
    notes: [
      "Frying the egusi properly in oil before adding liquid is what gives it that rich, nutty flavour.",
      "Don't over-stir once the vegetables go in — egusi soup is traditionally a little lumpy.",
      "Serve with pounded yam, eba, or fufu.",
    ],
  },
  {
    id: "salmon-herb",
    title: "Pan-Seared Salmon with Herb Butter",
    category: "European",
    time: "25 min",
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHxmb29kJTIwcGhvdG9ncmFwaHklMjBoZXJvJTIwZ291cm1ldCUyMG1lYWx8ZW58MXx8fHwxNzgyMDY3NDk2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Perfectly golden seared salmon with a dreamy herb butter sauce.",
    author: "Chizzy",
    rating: 4.7,
    saves: 1230,
    servings: 2,
    ingredients: [
      { amount: "2", item: "Salmon fillets, skin-on" },
      { amount: "2 tbsp", item: "Olive oil" },
      { amount: "3 tbsp", item: "Unsalted butter" },
      { amount: "2 cloves", item: "Garlic, minced" },
      { amount: "1 tbsp", item: "Fresh parsley, chopped" },
      { amount: "1 tsp", item: "Fresh thyme leaves" },
      { amount: "1", item: "Lemon, juiced + zested" },
      { amount: "Salt and pepper", item: "To taste" },
    ],
    steps: [
      { step: 1, title: "Season the salmon", time: "5 min", desc: "Pat salmon fillets dry and season generously with salt and pepper on both sides." },
      { step: 2, title: "Sear skin-side down", time: "6 min", desc: "Heat olive oil in a skillet over medium-high heat. Place salmon skin-side down and sear without moving until crisp, about 5–6 minutes." },
      { step: 3, title: "Flip and finish cooking", time: "3 min", desc: "Flip the salmon and cook for another 2–3 minutes until just cooked through." },
      { step: 4, title: "Make the herb butter", time: "3 min", desc: "Lower heat, add butter, garlic, thyme, and lemon zest to the pan. Baste the salmon with the melted herb butter for a minute." },
      { step: 5, title: "Finish and serve", time: "2 min", desc: "Squeeze fresh lemon juice over the top, sprinkle with parsley, and serve immediately." },
    ],
    notes: [
      "Don't move the salmon while searing skin-side down — that's what gives you the crispy skin.",
      "Pairs beautifully with roasted asparagus or a simple green salad.",
    ],
  },
  {
    id: "chocolate-cake",
    title: "Ultimate Chocolate Layer Cake",
    category: "Desserts",
    time: "1 hr 30 min",
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1615796701805-2094ac54bbf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHxkZXNzZXJ0cyUyMHBhc3RyaWVzJTIwY2FrZXMlMjBmb29kJTIwcGhvdG9ncmFwaHl8ZW58MXx8fHwxNzgyMDY3NDkzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Decadent three-layer chocolate cake with silky ganache frosting.",
    author: "Chizzy",
    rating: 4.9,
    saves: 3102,
    servings: 10,
    ingredients: [
      { amount: "2 cups", item: "All-purpose flour" },
      { amount: "2 cups", item: "Granulated sugar" },
      { amount: "¾ cup", item: "Unsweetened cocoa powder" },
      { amount: "2 tsp", item: "Baking soda" },
      { amount: "1 tsp", item: "Salt" },
      { amount: "2", item: "Large eggs" },
      { amount: "1 cup", item: "Buttermilk" },
      { amount: "1 cup", item: "Hot coffee or hot water" },
      { amount: "½ cup", item: "Vegetable oil" },
      { amount: "300g", item: "Dark chocolate, for ganache" },
      { amount: "300ml", item: "Heavy cream, for ganache" },
    ],
    steps: [
      { step: 1, title: "Mix dry ingredients", time: "5 min", desc: "Whisk together flour, sugar, cocoa powder, baking soda and salt in a large bowl." },
      { step: 2, title: "Add wet ingredients", time: "5 min", desc: "Beat in eggs and buttermilk, then slowly pour in the oil and hot coffee, mixing until smooth. The batter will be thin — that's normal." },
      { step: 3, title: "Bake the layers", time: "30 min", desc: "Divide batter between three greased 8-inch cake pans. Bake at 175°C (350°F) for 28–32 minutes until a skewer comes out clean. Cool completely." },
      { step: 4, title: "Make the ganache", time: "10 min", desc: "Heat the cream until just simmering, pour over chopped dark chocolate, and stir until smooth and glossy. Let cool until spreadable." },
      { step: 5, title: "Assemble and frost", time: "20 min", desc: "Stack the cooled layers with ganache between each, then frost the outside. Chill briefly to set before slicing." },
    ],
    notes: [
      "Hot coffee intensifies the chocolate flavour without making the cake taste like coffee.",
      "Make sure the cake layers are fully cool before frosting or the ganache will slide off.",
    ],
  },
  {
    id: "strawberry-cake",
    title: "Fresh Strawberry Summer Cake",
    category: "Desserts",
    time: "2 hrs",
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1629272040444-2f7553ec7466?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwzfHxkZXNzZXJ0cyUyMHBhc3RyaWVzJTIwY2FrZXMlMjBmb29kJTIwcGhvdG9ncmFwaHl8ZW58MXx8fHwxNzgyMDY3NDkzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Light and fluffy cake layered with fresh strawberries and cream.",
    author: "Chizzy",
    rating: 4.6,
    saves: 890,
    servings: 8,
    ingredients: [
      { amount: "2 ½ cups", item: "Cake flour" },
      { amount: "1 ¾ cups", item: "Granulated sugar" },
      { amount: "1 tbsp", item: "Baking powder" },
      { amount: "½ tsp", item: "Salt" },
      { amount: "4", item: "Large eggs" },
      { amount: "1 cup", item: "Whole milk" },
      { amount: "½ cup", item: "Unsalted butter, softened" },
      { amount: "2 cups", item: "Heavy whipping cream" },
      { amount: "3 cups", item: "Fresh strawberries, sliced" },
      { amount: "2 tbsp", item: "Sugar, for whipped cream" },
    ],
    steps: [
      { step: 1, title: "Make the cake batter", time: "10 min", desc: "Cream butter and sugar until fluffy, beat in eggs one at a time, then alternate adding the dry ingredients and milk." },
      { step: 2, title: "Bake the layers", time: "30 min", desc: "Divide between two greased 9-inch pans and bake at 175°C (350°F) for 25–30 minutes. Cool completely on a wire rack." },
      { step: 3, title: "Whip the cream", time: "5 min", desc: "Whip the heavy cream with sugar until soft peaks form." },
      { step: 4, title: "Macerate the strawberries", time: "10 min", desc: "Toss sliced strawberries with a little sugar and let sit for 10 minutes to draw out their juices." },
      { step: 5, title: "Assemble", time: "15 min", desc: "Layer cake, whipped cream, and strawberries, finishing with a final layer of cream and strawberries on top." },
    ],
    notes: [
      "Use the ripest strawberries you can find — this cake is all about the fruit.",
      "Best assembled a few hours before serving so the cream has time to set slightly.",
    ],
  },
  {
    id: "tropical-smoothie",
    title: "Tropical Mango Sunrise Smoothie",
    category: "Drinks",
    time: "10 min",
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1653542773369-51cce8d08250?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw0fHxjb2NrdGFpbCUyMGRyaW5rJTIwc21vb3RoaWUlMjBiZXZlcmFnZXxlbnwxfHx8fDE3ODIwNjc1MDF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "A vibrant tropical smoothie packed with mango, banana and a hint of ginger.",
    author: "Chizzy",
    rating: 4.5,
    saves: 560,
    servings: 2,
    ingredients: [
      { amount: "1 ½ cups", item: "Frozen mango chunks" },
      { amount: "1", item: "Ripe banana" },
      { amount: "½ cup", item: "Greek yogurt" },
      { amount: "¾ cup", item: "Orange juice" },
      { amount: "½ tsp", item: "Fresh grated ginger" },
      { amount: "1 tbsp", item: "Honey (optional)" },
    ],
    steps: [
      { step: 1, title: "Combine ingredients", time: "2 min", desc: "Add mango, banana, yogurt, orange juice, and ginger to a blender." },
      { step: 2, title: "Blend until smooth", time: "2 min", desc: "Blend on high until completely smooth, adding a splash more juice if it's too thick." },
      { step: 3, title: "Taste and serve", time: "1 min", desc: "Taste and add honey if you'd like it sweeter. Pour into glasses and serve immediately." },
    ],
    notes: [
      "Using frozen mango keeps the smoothie thick without needing extra ice.",
      "Great topped with chia seeds or coconut flakes.",
    ],
  },
  {
    id: "gourmet-bowl",
    title: "Rainbow Grain Bowl with Tahini",
    category: "American",
    time: "30 min",
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1552166539-ade937e98ed7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwzfHxmb29kJTIwcGhvdG9ncmFwaHklMjBoZXJvJTIwZ291cm1ldCUyMG1lYWx8ZW58MXx8fHwxNzgyMDY3NDk2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Nourishing, colourful and so satisfying — perfect weekday meal prep.",
    author: "Chizzy",
    rating: 4.7,
    saves: 720,
    servings: 2,
    ingredients: [
      { amount: "1 cup", item: "Cooked quinoa or brown rice" },
      { amount: "1 cup", item: "Roasted sweet potato cubes" },
      { amount: "1 cup", item: "Chickpeas, roasted" },
      { amount: "1 cup", item: "Shredded purple cabbage" },
      { amount: "1", item: "Avocado, sliced" },
      { amount: "3 tbsp", item: "Tahini" },
      { amount: "1 tbsp", item: "Lemon juice" },
      { amount: "1 tbsp", item: "Maple syrup" },
      { amount: "Salt and pepper", item: "To taste" },
    ],
    steps: [
      { step: 1, title: "Prep the grains and roast veg", time: "20 min", desc: "Cook quinoa according to package instructions. Roast sweet potato cubes and chickpeas at 200°C (400°F) for 20 minutes until golden." },
      { step: 2, title: "Make the tahini dressing", time: "5 min", desc: "Whisk together tahini, lemon juice, maple syrup, and a splash of water until smooth and pourable." },
      { step: 3, title: "Assemble the bowl", time: "5 min", desc: "Layer grains, roasted vegetables, cabbage, and avocado in a bowl. Drizzle generously with tahini dressing." },
    ],
    notes: [
      "Great for meal prep — keep the dressing separate until you're ready to eat.",
      "Swap in whatever vegetables you have on hand; this bowl is endlessly flexible.",
    ],
  },
  {
    id: "cooked-dish",
    title: "Slow-Cooked Oxtail Stew",
    category: "African",
    time: "3 hrs",
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1568600891621-50f697b9a1c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb29kJTIwcGhvdG9ncmFwaHklMjBoZXJvJTIwZ291cm1ldCUyMG1lYWx8ZW58MXx8fHwxNzgyMDY3NDk2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Melt-off-the-bone oxtail cooked low and slow in a rich tomato and spice base.",
    author: "Chizzy",
    rating: 4.9,
    saves: 2100,
    servings: 5,
    ingredients: [
      { amount: "1.5kg", item: "Oxtail, cut into pieces" },
      { amount: "1 large", item: "Onion, chopped" },
      { amount: "3", item: "Tomatoes, chopped" },
      { amount: "2 tbsp", item: "Tomato paste" },
      { amount: "3 cloves", item: "Garlic, minced" },
      { amount: "1 thumb", item: "Ginger, grated" },
      { amount: "2 cups", item: "Beef stock" },
      { amount: "2 tsp", item: "Smoked paprika" },
      { amount: "2", item: "Bay leaves" },
      { amount: "2 cubes", item: "Seasoning cubes" },
      { amount: "Salt and pepper", item: "To taste" },
    ],
    steps: [
      { step: 1, title: "Brown the oxtail", time: "15 min", desc: "Season oxtail with salt, pepper, and seasoning cubes. Brown well on all sides in a hot pot — this builds deep flavour." },
      { step: 2, title: "Build the base", time: "10 min", desc: "Add onions, garlic, and ginger to the same pot and sauté until fragrant. Stir in tomatoes, tomato paste, and paprika." },
      { step: 3, title: "Slow simmer", time: "2 hr 30 min", desc: "Return the oxtail to the pot, add beef stock and bay leaves. Cover and simmer on low heat for 2.5–3 hours until the meat is fall-off-the-bone tender, topping up liquid as needed." },
      { step: 4, title: "Reduce and serve", time: "10 min", desc: "Once tender, remove the lid and simmer uncovered for the last 10 minutes to thicken the sauce. Adjust seasoning and serve hot." },
    ],
    notes: [
      "Oxtail rewards patience — don't rush the simmer time.",
      "Tastes even better the next day once the flavours have settled.",
      "Serve with rice, mashed potatoes, or boiled plantain.",
    ],
  },
  {
    id: "coconut-pancakes",
    title: "Zoba's Coconut Pancakes",
    category: "American",
    time: "30 min",
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1579150877125-53b49ce88315?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw3fHxyZWNpcGUlMjBjb29raW5nJTIwa2l0Y2hlbiUyMGluZ3JlZGllbnRzfGVufDF8fHx8MTc4MjA2NzQ5Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Fluffy pancakes with a coconut twist — Chizzy's spin on a classic, makes about 12.",
    author: "Chizzy",
    rating: 4.8,
    saves: 640,
    servings: 4,
    ingredients: [
      { amount: "1 ½ cups", item: "All-purpose flour" },
      { amount: "2 tbsp", item: "Sugar" },
      { amount: "1 tbsp", item: "Aluminum-free baking powder" },
      { amount: "½ tsp", item: "Fine salt" },
      { amount: "1 ¼ cups", item: "Milk" },
      { amount: "1 large", item: "Egg" },
      { amount: "5 tbsp", item: "Unsalted butter, melted" },
      { amount: "To taste", item: "Coconut flakes" },
      { amount: "1 tsp", item: "Vanilla extract" },
      { amount: "1 tsp", item: "Coconut extract" },
    ],
    steps: [
      { step: 1, title: "Melt the butter", time: "3 min", desc: "Melt the butter and let it cool slightly." },
      { step: 2, title: "Mix dry and wet separately", time: "5 min", desc: "Whisk together flour, sugar, baking powder, and salt in one bowl. In another, whisk milk, egg, cooled butter, vanilla and coconut extract." },
      { step: 3, title: "Combine", time: "3 min", desc: "Pour the milk mixture into the center of the dry ingredients and whisk until just combined, leaving a few lumps." },
      { step: 4, title: "Cook the pancakes", time: "15 min", desc: "Preheat a greased skillet over medium heat. Pour about ¼ cup of batter per pancake. Cook until bubbles appear and edges look dry (2–3 min), flip, and cook until golden (30 sec)." },
      { step: 5, title: "Serve warm", time: "2 min", desc: "Keep cooked pancakes warm in a low oven while finishing the batter. Sprinkle with coconut flakes and serve with desired toppings." },
    ],
    notes: [
      "Don't overmix the batter — a few lumps make for fluffier pancakes.",
      "Toast the coconut flakes lightly for extra flavour.",
    ],
  },
  {
    id: "simple-pancakes",
    title: "Simple Everyday Pancakes",
    category: "American",
    time: "20 min",
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1518291344630-4857135fb581?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw1fHxyZWNpcGUlMjBjb29raW5nJTIwa2l0Y2hlbiUyMGluZ3JlZGllbnRzfGVufDF8fHx8MTc4MjA2NzQ5Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "A no-fail, fluffy pancake recipe that makes 8–10 medium pancakes.",
    author: "Chizzy",
    rating: 4.5,
    saves: 410,
    servings: 3,
    ingredients: [
      { amount: "1 cup (125g)", item: "All-purpose flour" },
      { amount: "2 tbsp", item: "Sugar" },
      { amount: "1 tsp", item: "Baking powder" },
      { amount: "¼ tsp", item: "Salt" },
      { amount: "1", item: "Egg" },
      { amount: "¾ cup (180ml)", item: "Milk" },
      { amount: "2 tbsp", item: "Melted butter or vegetable oil" },
      { amount: "1 tsp", item: "Vanilla extract (optional)" },
    ],
    steps: [
      { step: 1, title: "Mix dry ingredients", time: "3 min", desc: "Whisk together flour, sugar, baking powder, and salt." },
      { step: 2, title: "Mix wet ingredients", time: "3 min", desc: "Beat the egg, then add milk, melted butter, and vanilla." },
      { step: 3, title: "Combine and rest", time: "8 min", desc: "Pour wet into dry and stir gently until just combined. A few small lumps are fine. Let the batter rest for 5–10 minutes." },
      { step: 4, title: "Cook", time: "8 min", desc: "Heat a lightly oiled skillet over medium heat. Pour about ¼ cup batter per pancake, cook 2–3 minutes until bubbles form, flip, and cook another 1–2 minutes until golden." },
    ],
    notes: [
      "Use room-temperature ingredients and don't overmix for extra fluffy pancakes.",
      "Great with maple syrup, fresh fruit, or chocolate chips.",
    ],
  },
  {
    id: "nigerian-pancakes",
    title: "Zoba's Nigerian Pancakes",
    category: "Nigerian",
    time: "35 min",
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1591189863430-ab87e120f312?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwzfHxyZWNpcGUlMjBjb29raW5nJTIwa2l0Y2hlbiUyMGluZ3JlZGllbnRzfGVufDF8fHx8MTc4MjA2NzQ5Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Soft, slightly sweet and savoury thin pancakes — the classic Naija breakfast roll-up.",
    author: "Chizzy",
    rating: 4.7,
    saves: 980,
    servings: 4,
    ingredients: [
      { amount: "2 cups", item: "All-purpose flour" },
      { amount: "3 tbsp", item: "Sugar" },
      { amount: "½ tsp", item: "Salt" },
      { amount: "1 tsp", item: "Baking powder" },
      { amount: "2", item: "Eggs" },
      { amount: "1 ½–2 cups", item: "Milk (or evaporated milk + water)" },
      { amount: "2 tbsp", item: "Melted butter or vegetable oil" },
      { amount: "½ tsp", item: "Nutmeg" },
      { amount: "½ cup", item: "Finely chopped onions" },
      { amount: "½ cup", item: "Shredded carrots" },
      { amount: "¼ cup", item: "Chopped bell peppers" },
      { amount: "Fresh pepper", item: "Chopped, to taste" },
    ],
    steps: [
      { step: 1, title: "Mix dry ingredients", time: "3 min", desc: "Combine flour, sugar, salt, baking powder, and nutmeg in a bowl." },
      { step: 2, title: "Add wet ingredients", time: "5 min", desc: "Crack in the eggs, then gradually add milk, stirring until smooth and lump-free." },
      { step: 3, title: "Fold in veg and protein", time: "5 min", desc: "Add onions, carrots, peppers, and any optional protein. Mix in melted butter and vanilla if using. The batter should be light and slightly runny." },
      { step: 4, title: "Rest the batter", time: "8 min", desc: "Let it sit for 5–10 minutes so it relaxes for softer pancakes." },
      { step: 5, title: "Cook thin and roll", time: "14 min", desc: "Heat a lightly greased pan over medium heat. Pour a small amount of batter and tilt the pan to spread thin. Cook 1–2 minutes per side, then roll up Naija style." },
    ],
    notes: [
      "Nutmeg is what gives it that authentic Nigerian flavour — don't skip it.",
      "Keep the batter thin and spreadable, not thick like cake batter.",
      "Serve rolled up with fried eggs, sausages, or tea.",
    ],
  },
  {
    id: "smoky-jollof",
    title: "Zoba's Smoky Jollof Rice",
    category: "Nigerian",
    time: "1 hr 30 min",
    difficulty: "Hard",
    image: "https://images.unsplash.com/photo-1665593998976-d957f2827fe7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHxyaWNlJTIwc3RldyUyMHNvdXAlMjBib3dsJTIwZm9vZHxlbnwxfHx8fDE3ODIwNjc1MDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Deep, smoky party jollof made with steamed fresh vegetables and a controlled-burn finish.",
    author: "Chizzy",
    rating: 4.9,
    saves: 1560,
    servings: 8,
    ingredients: [
      { amount: "900g", item: "Ripe tomatoes" },
      { amount: "1 large", item: "Red bell pepper" },
      { amount: "1 large", item: "Red/purple onion" },
      { amount: "2", item: "Scotch bonnet peppers" },
      { amount: "2 cloves", item: "Garlic" },
      { amount: "1 thumb", item: "Fresh ginger" },
      { amount: "2 ½ cups", item: "Parboiled rice" },
      { amount: "2 cups", item: "Meat stock" },
      { amount: "½ cup", item: "Vegetable oil" },
      { amount: "2 tbsp", item: "Red oil / sesame oil" },
      { amount: "2 packets", item: "Tomato paste" },
      { amount: "5", item: "Bay leaves" },
      { amount: "2 tsp", item: "Dried thyme" },
      { amount: "2 tsp", item: "Curry powder" },
    ],
    steps: [
      { step: 1, title: "Steam the vegetables", time: "35 min", desc: "Place chopped tomatoes, bell peppers, onions, scotch bonnet, garlic, ginger and salt in a pot. Cover and cook on medium heat without added liquid until the vegetables soften and dry out. Cool, then blend into a paste." },
      { step: 2, title: "Fry the tomato base", time: "15 min", desc: "Heat vegetable and red oil, fry the tomato paste until it separates, add chopped onions and fry until lightly browned, then pour in the blended tomato mixture and fry for 5 minutes." },
      { step: 3, title: "Season and add rice", time: "5 min", desc: "Stir in thyme, curry powder, ginger and paprika. Rinse the rice and add it along with bay leaves and meat stock. Bring to a boil." },
      { step: 4, title: "Steam covered", time: "20 min", desc: "Cover the pot with foil then the lid, and simmer until most of the liquid is absorbed. Stir from the bottom, re-cover with foil and lid, and cook another 10–15 minutes until soft but firm." },
      { step: 5, title: "Controlled burn for smoky flavour", time: "8 min", desc: "Increase the heat for 5–8 minutes to let the rice catch slightly at the bottom — this is what gives smoky jollof its signature aroma." },
    ],
    notes: [
      "Sealing the pot with foil before the lid traps steam and intensifies the smoky aroma.",
      "Use a heavy, non-stick-free pot so the rice can catch slightly at the bottom.",
      "Serve with fried plantains, grilled chicken, or coleslaw.",
    ],
  },
  {
    id: "samosa-spring-rolls",
    title: "Samosa & Spring Rolls",
    category: "Asian",
    time: "1 hr",
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2NrdGFpbCUyMGRyaW5rJTIwc21vb3RoaWUlMjJiZXZlcmFnZXxlbnwxfHx8fDE3ODIwNjc1MDF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Crispy homemade samosas and spring rolls with savoury potato and vegetable fillings.",
    author: "Chizzy",
    rating: 4.6,
    saves: 730,
    servings: 6,
    ingredients: [
      { amount: "2 cups", item: "All-purpose flour (for wrappers)" },
      { amount: "1 ½ cups", item: "Water" },
      { amount: "¼ tsp", item: "Salt" },
      { amount: "2–3", item: "Potatoes, boiled and mashed" },
      { amount: "½ cup", item: "Boiled peas" },
      { amount: "1", item: "Onion, finely chopped" },
      { amount: "1 cup", item: "Shredded cabbage" },
      { amount: "1 cup", item: "Julienned carrots" },
      { amount: "1 tbsp", item: "Soy sauce" },
      { amount: "1 tsp", item: "Sesame oil" },
      { amount: "Oil for frying", item: "As needed" },
    ],
    steps: [
      { step: 1, title: "Make the wrappers", time: "20 min", desc: "Whisk flour, salt, and water into a thin, lump-free batter. Cook thin sheets on a non-stick pan over low heat for 30–60 seconds until dry. Cover with a damp cloth." },
      { step: 2, title: "Make the samosa filling", time: "10 min", desc: "Mix mashed potatoes with peas, onion, seasoning cube, oregano, chili powder and salt." },
      { step: 3, title: "Make the spring roll filling", time: "10 min", desc: "Sauté cabbage, carrots, and green onions with soy sauce, sesame oil, garlic powder, salt and pepper." },
      { step: 4, title: "Assemble both", time: "15 min", desc: "Cut wrapper strips into cones for samosas, fill, and seal with a flour-water paste. For spring rolls, place filling in the center of a square wrapper, fold, tuck, and roll tightly." },
      { step: 5, title: "Fry until golden", time: "8 min", desc: "Heat oil to medium and fry in batches until golden brown and crispy, about 3–5 minutes. Drain on paper towels." },
    ],
    notes: [
      "Fry on medium-low heat so the inside cooks through without burning the outside.",
      "Unused wrappers keep in the fridge for up to 3 days or freeze well.",
    ],
  },
  {
    id: "chicken-dumplings",
    title: "Zoba's Chicken Dumplings",
    category: "Asian",
    time: "1 hr 15 min",
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1674649203068-e9fd9c4a5620?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw0fHxmb29kJTIwcGhvdG9ncmFwaHklMjBoZXJvJTIwZ291cm1ldCUyMG1lYWx8ZW58MXx8fHwxNzgyMDY3NDk2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Classic homemade chicken dumplings with cabbage and carrots, with a tangy dipping sauce.",
    author: "Chizzy",
    rating: 4.8,
    saves: 845,
    servings: 4,
    ingredients: [
      { amount: "500g", item: "Ground chicken" },
      { amount: "2 cups", item: "Cabbage, finely chopped" },
      { amount: "1 medium", item: "Carrot, grated" },
      { amount: "2", item: "Spring onions, sliced" },
      { amount: "2 cloves", item: "Garlic, minced" },
      { amount: "1 tsp", item: "Fresh ginger, grated" },
      { amount: "1 tbsp", item: "Soy sauce" },
      { amount: "1 tsp", item: "Sesame oil" },
      { amount: "2 cups", item: "All-purpose flour (for wrappers)" },
      { amount: "¾ cup", item: "Warm water" },
    ],
    steps: [
      { step: 1, title: "Prepare the filling", time: "15 min", desc: "Salt the chopped cabbage and let sit 10 minutes, then squeeze out excess water. Combine with carrot, spring onions, garlic, ginger, soy sauce, sesame oil, salt and pepper." },
      { step: 2, title: "Make the dough", time: "15 min", desc: "Mix flour, salt and warm water into a shaggy dough. Knead 8–10 minutes until smooth, then rest covered for 30 minutes." },
      { step: 3, title: "Wrap the dumplings", time: "20 min", desc: "Roll the dough into a rope, cut into pieces, and roll each into an 8–10cm circle. Add filling, moisten the edge, fold and pinch to seal." },
      { step: 4, title: "Cook", time: "15 min", desc: "Steam for 12–15 minutes, or pan-fry the bottoms golden then add a splash of water, cover, and steam-fry 6–8 minutes, or boil 6–8 minutes until they float." },
      { step: 5, title: "Make the dipping sauce", time: "3 min", desc: "Mix soy sauce, rice vinegar, grated ginger, and optional chili oil." },
    ],
    notes: [
      "Squeezing the water out of the cabbage is essential to avoid soggy dumplings.",
      "These freeze beautifully — freeze in a single layer first, then bag for up to 3 months.",
    ],
  },
  {
    id: "homemade-pizza",
    title: "Homemade Chicken, Pepper & Onion Pizza",
    category: "European",
    time: "2 hr 30 min",
    difficulty: "Medium",
    image: "/images/recipes/chicken-pepper-pizza.png",
    excerpt: "Thick, crisp and chewy homemade crust topped with seasoned chicken, peppers and two cheeses.",
    author: "Chizzy",
    rating: 4.8,
    saves: 1120,
    servings: 8,
    ingredients: [
      { amount: "1 ⅓ cups", item: "Warm water" },
      { amount: "1 tbsp", item: "Granulated sugar" },
      { amount: "2 ¼ tsp", item: "Instant yeast" },
      { amount: "3 ½–4 cups", item: "All-purpose flour" },
      { amount: "2 tbsp", item: "Olive oil" },
      { amount: "1 tsp", item: "Salt" },
      { amount: "2", item: "Chicken breasts, diced" },
      { amount: "1 cup", item: "Pizza sauce" },
      { amount: "2 cups", item: "Shredded mozzarella" },
      { amount: "2 cups", item: "Shredded cheddar" },
      { amount: "1", item: "Red bell pepper, sliced" },
      { amount: "1", item: "Onion, sliced" },
    ],
    steps: [
      { step: 1, title: "Activate the yeast", time: "5 min", desc: "Combine warm water, sugar, and yeast. Let sit until foamy." },
      { step: 2, title: "Make and knead the dough", time: "10 min", desc: "Add flour, olive oil, and salt. Mix into a soft dough, then knead 5–8 minutes until smooth and elastic." },
      { step: 3, title: "Let it rise", time: "75 min", desc: "Place in an oiled bowl, cover, and let rise in a warm place for 60–90 minutes until doubled." },
      { step: 4, title: "Cook the chicken topping", time: "8 min", desc: "Toss diced chicken with garlic powder, paprika, salt and pepper, then cook in olive oil until just done." },
      { step: 5, title: "Shape, top and bake", time: "20 min", desc: "Preheat oven to 246°C (475°F). Divide dough, shape into circles, top with sauce, cheese, chicken, peppers and onions. Bake 13–15 minutes until golden and bubbling." },
    ],
    notes: [
      "Unused dough freezes well for up to 3 months after the first rise.",
      "Finish with Italian seasoning or chili flakes for extra flavour.",
    ],
  },
  {
    id: "creamy-chicken-pasta",
    title: "Creamy Chicken Penne Pasta",
    category: "European",
    time: "40 min",
    difficulty: "Medium",
    image: "/images/recipes/creamy-penne-pasta.png",
    excerpt: "Creamy chicken penne with tomatoes, bell peppers, cheddar and mozzarella.",
    author: "Chizzy",
    rating: 4.7,
    saves: 690,
    servings: 5,
    ingredients: [
      { amount: "300–400g", item: "Penne pasta" },
      { amount: "2", item: "Chicken breasts, diced" },
      { amount: "1 medium", item: "Onion, diced" },
      { amount: "3 cloves", item: "Garlic, minced" },
      { amount: "2 medium", item: "Tomatoes, diced" },
      { amount: "1", item: "Red bell pepper, diced" },
      { amount: "1", item: "Green bell pepper, diced" },
      { amount: "1 cup", item: "Cooking cream" },
      { amount: "1 cup", item: "Shredded cheddar" },
      { amount: "½ cup", item: "Shredded mozzarella" },
      { amount: "2–3 tbsp", item: "Chili sauce" },
    ],
    steps: [
      { step: 1, title: "Cook the pasta", time: "12 min", desc: "Boil penne in salted water until al dente, reserving ½ cup of pasta water before draining." },
      { step: 2, title: "Cook the chicken", time: "8 min", desc: "Season diced chicken with paprika, oregano, salt and pepper, then cook in oil until golden and cooked through. Set aside." },
      { step: 3, title: "Build the sauce", time: "10 min", desc: "Sauté onions and garlic, then add tomatoes and bell peppers and cook until softened. Stir in oregano and chili sauce." },
      { step: 4, title: "Add cream and cheese", time: "5 min", desc: "Lower the heat, stir in the cream, then gradually melt in the cheddar. Loosen with reserved pasta water if needed, then stir in half the mozzarella." },
      { step: 5, title: "Combine and finish", time: "5 min", desc: "Return the chicken and pasta to the pan and toss to coat. Top with remaining mozzarella, cover briefly to melt, and serve." },
    ],
    notes: [
      "Reserved pasta water is the easiest way to loosen a sauce that's gotten too thick.",
      "Pairs well with garlic bread or a simple side salad.",
    ],
  },
  {
    id: "cheesy-chicken-sandwiches",
    title: "Cheesy Chicken & Sausage Sandwiches",
    category: "American",
    time: "30 min",
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1674649203068-e9fd9c4a5620?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw0fHxmb29kJTIwcGhvdG9ncmFwaHklMjBoZXJvJTIwZ291cm1ldCUyMG1lYWx8ZW58MXx8fHwxNzgyMDY3NDk2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Toasted, cheesy sandwiches loaded with chicken, sausage and crunchy vegetables.",
    author: "Chizzy",
    rating: 4.6,
    saves: 520,
    servings: 4,
    ingredients: [
      { amount: "8–12 slices", item: "Bread" },
      { amount: "1", item: "Chicken breast, cooked and shredded" },
      { amount: "2", item: "Sausages, diced and cooked" },
      { amount: "1 cup", item: "Cabbage, finely shredded" },
      { amount: "1", item: "Carrot, grated" },
      { amount: "½ cup", item: "Mayonnaise" },
      { amount: "2 tbsp", item: "Ketchup" },
      { amount: "1 cup", item: "Cheddar cheese, grated" },
      { amount: "1 cup", item: "Mozzarella cheese, grated" },
    ],
    steps: [
      { step: 1, title: "Sauté the filling", time: "8 min", desc: "Sauté onion and garlic, then add shredded chicken and sausage. Stir in cabbage and carrot, cooking just until slightly softened." },
      { step: 2, title: "Mix the sauce", time: "3 min", desc: "Combine mayonnaise and ketchup, then fold half into the chicken mixture." },
      { step: 3, title: "Assemble", time: "5 min", desc: "Spread remaining sauce on bread slices, add the filling, and top generously with both cheeses before closing with another slice." },
      { step: 4, title: "Toast", time: "8 min", desc: "Toast in a sandwich maker, oven, or pan until golden and the cheese melts." },
    ],
    notes: [
      "Letting the filling cool slightly before assembling keeps the bread from going soggy.",
    ],
  },
  {
    id: "pizza-ball-rolls",
    title: "Cheesy Pizza Ball Rolls",
    category: "Budget Meals",
    time: "1 hr 45 min",
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1579150877125-53b49ce88315?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw3fHxyZWNpcGUlMjBjb29raW5nJTIwa2l0Y2hlbiUyMGluZ3JlZGllbnRzfGVufDF8fHx8MTc4MjA2NzQ5Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    excerpt: "Soft bread rolls stuffed with pizza-style chicken, sausage, vegetables and cheese.",
    author: "Chizzy",
    rating: 4.7,
    saves: 610,
    servings: 8,
    ingredients: [
      { amount: "2 cups", item: "All-purpose flour" },
      { amount: "1 tsp", item: "Instant yeast" },
      { amount: "1 tbsp", item: "Sugar" },
      { amount: "¾ cup", item: "Warm water" },
      { amount: "1", item: "Chicken breast, cooked and shredded" },
      { amount: "2", item: "Sausages, diced" },
      { amount: "1 cup", item: "Cabbage, finely chopped" },
      { amount: "1", item: "Carrot, grated" },
      { amount: "2 tbsp", item: "Ketchup" },
      { amount: "2 tbsp", item: "Mayonnaise" },
      { amount: "1 cup", item: "Cheddar cheese, grated" },
      { amount: "1 cup", item: "Mozzarella cheese, grated" },
    ],
    steps: [
      { step: 1, title: "Make the dough", time: "70 min", desc: "Mix warm water, sugar and yeast, let stand 5 minutes, then add flour, salt and oil. Knead 5–8 minutes and let rise for 1 hour." },
      { step: 2, title: "Make the filling", time: "10 min", desc: "Sauté onion and garlic, add chicken and sausage, stir in cabbage and carrot, then cool and mix in ketchup, mayonnaise and half the cheese." },
      { step: 3, title: "Assemble the rolls", time: "20 min", desc: "Divide dough into 8–10 portions, flatten, add filling and extra cheese, pinch closed, and roll into balls." },
      { step: 4, title: "Bake", time: "25 min", desc: "Let rolls rise 20–30 minutes, brush with egg wash, then bake at 180°C (350°F) for 18–22 minutes until golden." },
    ],
    notes: [
      "These freeze well — a great make-ahead snack or party food.",
      "Serve warm with mayonnaise, ketchup, or garlic mayo.",
    ],
  },
  {
    id: "korean-hotteok",
    title: "Korean Hotteok (Sweet Filled Pancakes)",
    category: "Asian",
    time: "2 hrs",
    difficulty: "Medium",
    image: "/images/recipes/korean-hotteok.png",
    excerpt: "Soft, chewy Korean street food pancakes with a molten brown sugar and cinnamon filling.",
    author: "Chizzy",
    rating: 4.6,
    saves: 380,
    servings: 6,
    ingredients: [
      { amount: "2 cups (250g)", item: "All-purpose flour" },
      { amount: "1 tsp", item: "Instant yeast" },
      { amount: "1 tbsp", item: "Sugar" },
      { amount: "½ tsp", item: "Salt" },
      { amount: "¾ cup (180ml)", item: "Warm milk or water" },
      { amount: "1 tbsp", item: "Vegetable oil" },
      { amount: "½ cup", item: "Brown sugar (filling)" },
      { amount: "1 tsp", item: "Cinnamon" },
      { amount: "¼ cup", item: "Chopped mixed nuts (optional)" },
    ],
    steps: [
      { step: 1, title: "Make the dough", time: "90 min", desc: "Mix warm milk, sugar and yeast, let sit 5 minutes, then add flour, salt and oil. Mix into a sticky dough and let rise 1–2 hours until doubled." },
      { step: 2, title: "Prepare the filling", time: "3 min", desc: "Mix brown sugar, cinnamon, and chopped nuts." },
      { step: 3, title: "Shape", time: "15 min", desc: "Divide dough into 6–8 pieces, flatten, add a tablespoon of filling, and pinch the edges to seal into a ball." },
      { step: 4, title: "Cook", time: "12 min", desc: "Place seam-side down in an oiled pan over medium heat, cook 30 seconds, then press flat with a spatula and cook 2–3 minutes per side until golden." },
    ],
    notes: [
      "Be careful when eating — the melted sugar filling stays very hot.",
      "Try a savoury version with mozzarella, shredded chicken, or kimchi and cheese.",
    ],
  },
  {
    id: "boba-milk-chamomile-tea",
    title: "Boba Milk Chamomile Tea",
    category: "Drinks",
    time: "25 min",
    difficulty: "Easy",
    image: "/images/recipes/boba-milk-tea.png",
    excerpt: "A cosy twist on milk tea — chewy boba pearls under chamomile tea and cold milk, finished with whipped cream.",
    author: "Chizzy",
    rating: 4.7,
    saves: 410,
    servings: 2,
    ingredients: [
      { amount: "½ cup", item: "Boba (tapioca) pearls" },
      { amount: "3 tbsp", item: "Brown sugar (for boba syrup)" },
      { amount: "2", item: "Chamomile tea bags" },
      { amount: "1 cup", item: "Hot water (to steep tea)" },
      { amount: "1 ½ cups", item: "Cold milk" },
      { amount: "2 tbsp", item: "Condensed milk (or to taste)" },
      { amount: "1 cup", item: "Ice cubes" },
      { amount: "Whipped cream", item: "To top" },
      { amount: "Crushed cookies or chocolate chips", item: "To garnish (optional)" },
    ],
    steps: [
      { step: 1, title: "Cook the boba", time: "10 min", desc: "Boil the boba pearls according to the package instructions until soft and chewy. Drain and toss immediately in the brown sugar while still hot, letting it melt into a glossy syrup coating." },
      { step: 2, title: "Steep the chamomile tea", time: "5 min", desc: "Steep the chamomile tea bags in hot water for 5 minutes, then let cool slightly. Chill in the fridge if you have time." },
      { step: 3, title: "Layer the boba", time: "2 min", desc: "Spoon the brown-sugar boba into the bottom of two glasses or mason jars, letting some syrup drip down the sides." },
      { step: 4, title: "Add ice, tea and milk", time: "3 min", desc: "Fill the glasses with ice, pour over the chamomile tea, then top up with cold milk and condensed milk to taste. Stir gently." },
      { step: 5, title: "Top and serve", time: "2 min", desc: "Finish with a swirl of whipped cream and a scatter of crushed cookies or chocolate chips. Serve with a wide straw for the boba." },
    ],
    notes: [
      "Fresh-cooked boba is best eaten within a few hours — it firms up and gets less chewy once fully cooled.",
      "Swap chamomile for jasmine or black tea if you want a stronger, more traditional milk tea base.",
    ],
  },
  {
    id: "dumplings-noodles-two-ways",
    title: "Dumplings & Noodles, Two Ways (Boiled + Potsticker)",
    category: "Asian",
    time: "1 hr 30 min",
    difficulty: "Medium",
    image: "/images/recipes/dumplings-noodles.png",
    galleryImages: ["/images/recipes/dumplings-noodles.png", "/images/recipes/dumplings-noodles-boiled.png"],
    excerpt: "One dumpling filling, two ways to enjoy it — half boiled into a comforting noodle soup, half pan-fried into crispy potstickers.",
    author: "Chizzy",
    rating: 4.9,
    saves: 960,
    servings: 4,
    ingredients: [
      { amount: "500g", item: "Ground pork or chicken" },
      { amount: "2 cups", item: "Cabbage, finely chopped" },
      { amount: "2", item: "Spring onions, sliced" },
      { amount: "2 cloves", item: "Garlic, minced" },
      { amount: "1 tsp", item: "Fresh ginger, grated" },
      { amount: "1 tbsp", item: "Soy sauce" },
      { amount: "1 tsp", item: "Sesame oil" },
      { amount: "30–35", item: "Dumpling/gyoza wrappers" },
      { amount: "2 portions", item: "Fresh egg noodles or ramen noodles" },
      { amount: "4 cups", item: "Chicken or pork broth" },
      { amount: "2", item: "Soft-boiled eggs (for the soup bowls)" },
      { amount: "Chili oil, sesame seeds, scallions", item: "To garnish" },
      { amount: "2 tbsp", item: "Neutral oil (for frying)" },
    ],
    steps: [
      { step: 1, title: "Make the filling", time: "15 min", desc: "Salt the chopped cabbage and let it sit 10 minutes, then squeeze out the excess water. Mix with the ground pork or chicken, spring onions, garlic, ginger, soy sauce, sesame oil, salt and pepper." },
      { step: 2, title: "Wrap the dumplings", time: "25 min", desc: "Spoon a small amount of filling into the centre of each wrapper, moisten the edge with water, fold in half and pleat or pinch to seal. Set aside on a floured tray, keeping half and half for the two cooking methods." },
      { step: 3, title: "Boil one batch for the noodle soup", time: "15 min", desc: "Bring the broth to a simmer. Cook the noodles separately according to package instructions, then divide between bowls. Boil half the dumplings in the simmering broth for 6–8 minutes until they float and are cooked through, then ladle the broth and dumplings over the noodles. Top with a soft-boiled egg, scallions and chili oil." },
      { step: 4, title: "Pan-fry the rest as potstickers", time: "10 min", desc: "Heat oil in a non-stick pan over medium heat. Arrange the remaining dumplings flat-side down and fry 2–3 minutes until golden, then add a splash of water, cover, and steam-fry for 4–5 minutes until cooked through and crisp on the bottom." },
      { step: 5, title: "Serve both together", time: "2 min", desc: "Plate the potstickers with a simple soy-vinegar dipping sauce alongside the bowl of dumpling noodle soup, so everyone gets to try both styles." },
    ],
    notes: [
      "Squeezing the water out of the cabbage is essential to avoid soggy filling.",
      "Freeze any extra uncooked dumplings in a single layer before bagging — cook straight from frozen, no need to thaw.",
    ],
  },
  {
    id: "sorbet-fruit-blend-milk-frappe",
    title: "Sorbet Fruit Blend & Milk Frappe",
    category: "Drinks",
    time: "20 min",
    difficulty: "Easy",
    image: "/images/recipes/sorbet-fruit-milk-frappe.png",
    excerpt: "A layered, chilled treat — real fruit sorbet on the bottom, a creamy milk frappe on top. Refreshing, light and made with real fruit.",
    author: "Chizzy",
    rating: 4.8,
    saves: 540,
    servings: 4,
    ingredients: [
      { amount: "1 cup", item: "Melon, cubed and frozen" },
      { amount: "1 cup", item: "Pineapple, cubed and frozen" },
      { amount: "1", item: "Banana, sliced and frozen" },
      { amount: "1 cup", item: "Mango, cubed and frozen" },
      { amount: "2–3 tbsp", item: "Honey or sugar (for the sorbet)" },
      { amount: "2 cups", item: "Milk, cold" },
      { amount: "1 ½ cups", item: "Ice cubes" },
      { amount: "3 tbsp", item: "Condensed milk or sugar (for the frappe)" },
      { amount: "Fresh mint leaves", item: "To garnish" },
    ],
    steps: [
      { step: 1, title: "Blend the fruit sorbet", time: "5 min", desc: "Blend the frozen melon, pineapple, banana and mango with the honey or sugar until smooth and thick like soft-serve. Spoon into the fridge or freezer briefly to firm up while you make the frappe." },
      { step: 2, title: "Blend the milk frappe", time: "5 min", desc: "Blend the cold milk, ice and condensed milk (or sugar) until frothy and slushy." },
      { step: 3, title: "Layer it up", time: "5 min", desc: "Spoon the fruit sorbet into the bottom third of each glass or jar, pressing gently to level it." },
      { step: 4, title: "Top with the frappe", time: "3 min", desc: "Pour the milk frappe over the sorbet layer, filling each glass most of the way." },
      { step: 5, title: "Garnish and serve", time: "2 min", desc: "Finish with a final scoop of fruit sorbet on top and a sprig of fresh mint. Serve immediately with a spoon and a straw." },
    ],
    notes: [
      "Freezing the fruit ahead of time is what gives the sorbet layer its thick, scoopable texture — fresh fruit alone will blend too thin.",
      "Mix and match whichever fruit you have frozen on hand — this works well with most soft tropical fruits.",
    ],
  },
  {
    id: "homemade-boba-milk-chamomile-tea",
    title: "Homemade Boba Milk Chamomile Tea",
    category: "Drinks",
    time: "1 hr",
    difficulty: "Medium",
    image: "/images/recipes/homemade-boba-chamomile-tea.png",
    excerpt: "Chewy tapioca boba made completely from scratch, layered under chamomile-infused milk tea and topped with whipped cream and chocolate chips.",
    author: "Chizzy",
    rating: 4.9,
    saves: 280,
    servings: 2,
    ingredients: [
      { amount: "½ cup", item: "Tapioca starch (plus extra for dusting)" },
      { amount: "2 tbsp", item: "Brown sugar (for the boba dough)" },
      { amount: "3 tbsp", item: "Boiling water (for the boba dough)" },
      { amount: "3 tbsp", item: "Brown sugar (for the syrup coating)" },
      { amount: "2 tbsp", item: "Water (for the syrup coating)" },
      { amount: "2", item: "Chamomile tea bags" },
      { amount: "1 cup", item: "Hot water (to steep the tea)" },
      { amount: "1 ½ cups", item: "Cold milk" },
      { amount: "2 tbsp", item: "Condensed milk (or to taste)" },
      { amount: "1 cup", item: "Ice cubes" },
      { amount: "Whipped cream", item: "To top" },
      { amount: "Mini chocolate chips", item: "To garnish" },
    ],
    steps: [
      { step: 1, title: "Make the boba dough", time: "10 min", desc: "Dissolve the 2 tbsp brown sugar in the boiling water, then pour it into the tapioca starch while stirring quickly with a spoon. Once it's cool enough to handle, knead by hand until you get a smooth, dark, slightly sticky dough." },
      { step: 2, title: "Roll the pearls", time: "15 min", desc: "Pinch off small pea-sized pieces of dough and roll between your palms into round balls, dusting your hands and a tray with tapioca starch so they don't stick together as you go." },
      { step: 3, title: "Cook the pearls", time: "20 min", desc: "Bring a pot of water to a boil and drop in the pearls, stirring gently so they don't stick to the bottom. Boil until they float (about 5 minutes), then reduce to a simmer and cook a further 10–15 minutes until fully translucent and chewy. Drain." },
      { step: 4, title: "Coat in syrup", time: "5 min", desc: "Warm the remaining brown sugar and water in a small pan until syrupy, then toss the drained pearls through it so they're glossy and won't clump as they cool." },
      { step: 5, title: "Steep the chamomile tea", time: "5 min", desc: "Steep the chamomile tea bags in the hot water for 5 minutes, then let cool slightly." },
      { step: 6, title: "Assemble and top", time: "5 min", desc: "Spoon the syrup-coated boba into the bottom of two glasses, fill with ice, pour over the chamomile tea, then top up with cold milk and condensed milk to taste. Finish with a generous swirl of whipped cream and a scatter of mini chocolate chips. Serve with a wide straw." },
    ],
    notes: [
      "Homemade boba is best eaten the same day — it firms up and loses its chew once refrigerated overnight.",
      "If the dough cracks while rolling, knead in a few more drops of hot water until it's smooth and pliable again.",
    ],
  },
];
